module

public import ProvabilityLogic.Gentzen.A.Kripke
public import ProvabilityLogic.Logic.D.Basic
public import ProvabilityLogic.ProvabilityLogic.Classification.GeneralTrace

/-!
# Artemov's logic `A`

`LogicA` (Artemov's `GLαω`) is `GL` extended by every instance `TBB n` of the scheme
`□^[n + 1]⊥ 🡒 □^[n]⊥`. Equivalently, it is `GL` extended by every iterated consistency
statement `∼□^[n]⊥`. This file develops:

- two induction principles avoiding the substitution rule, `LogicA.substlessInductionTBB`
  and `LogicA.substlessInductionGP`, one for each of these axiomatizations;
- the deduction-theorem characterization
  `LogicA.iff_provable_provable_GL_neg_boxItr_bot_imp`: a formula is a theorem of `LogicA`
  iff `GL` proves `∼□^[n]⊥ 🡒 A` for some `n`;
- ω-model completeness, `LogicA.iff_provable_forces_graftOmega_root`, where the ω-models
  are the models `M.graftOmega a` built from finite rooted `GL` models;
- `LogicA_ssubset_LogicD`: `LogicA` is a proper sublogic of Dzhaparidze's `LogicD`.
-/

@[expose]
public section

universe u
variable {α : Type u}

/-- **Artemov's logic `A`** (also written `GLαω = GLα ω`): `GL` extended by all `TBB n`. -/
abbrev LogicA {α} : Logic α := LogicGLAlpha Set.univ

namespace LogicA

open LogicGL

section

/-- The intrinsic definition of `LogicA` that avoids `subst`, generated by the axioms
`TBB n` (used for `LogicA.substlessInductionTBB`). -/
protected inductive substlessTBB : Logic α
  | GL {A} : A ∈ LogicGL → LogicA.substlessTBB A
  | TBB (n : ℕ) : LogicA.substlessTBB (TBB n)
  | mdp {A B} : LogicA.substlessTBB (A 🡒 B) → LogicA.substlessTBB A → LogicA.substlessTBB B

variable {A : Formula α}

@[grind →]
lemma provable_of_provable_GL (h : A ∈ LogicGL) : A ∈ LogicA := Logic.sumQuasiNormal.mem₁ h

lemma provable_axiomTBB (n : ℕ) : (TBB n : Formula α) ∈ LogicA :=
  Logic.sumQuasiNormal.mem₂ ⟨TBB n, ⟨n, by simp, rfl⟩, by simp⟩

private lemma substlessTBB.eq_LogicA : LogicA.substlessTBB (α := α) = LogicA := by
  ext A;
  constructor;
  . intro h;
    induction h with
    | GL h => exact provable_of_provable_GL h;
    | TBB n => exact provable_axiomTBB n;
    | mdp _ _ ihAB ihA => exact Logic.sumQuasiNormal.mdp ihAB ihA;
  . intro h;
    induction h with
    | mem₁ h => exact LogicA.substlessTBB.GL h;
    | mem₂ h =>
      obtain ⟨B, ⟨n, -, rfl⟩, hB⟩ := h;
      obtain rfl : _root_.TBB n = _ := by simpa using hB;
      exact LogicA.substlessTBB.TBB n;
    | mdp _ _ ihAB ihA => exact LogicA.substlessTBB.mdp ihAB ihA;
    | subst hA ihA =>
      clear hA;
      induction ihA with
      | GL h => exact LogicA.substlessTBB.GL (ProvableHilbert.subst h);
      | TBB n =>
        simp only [_root_.TBB, Formula.subst_imp, Formula.subst_boxItr, Formula.subst_bot];
        exact LogicA.substlessTBB.TBB n;
      | mdp _ _ ihAB ihA => exact LogicA.substlessTBB.mdp ihAB ihA;

private lemma substlessTBB.toLogicA (h : LogicA.substlessTBB A) : A ∈ LogicA :=
  LogicA.substlessTBB.eq_LogicA ▸ h

private lemma substlessTBB.ofLogicA (h : A ∈ LogicA) : LogicA.substlessTBB A :=
  LogicA.substlessTBB.eq_LogicA.symm ▸ h

/-- Induction principle for `LogicA` avoiding `subst`: it suffices to handle the `GL`
fragment, the axioms `TBB n`, and `mdp`. -/
protected lemma substlessInductionTBB
  {motive : (A : Formula α) → A ∈ LogicA → Prop}
  (GL : ∀ {A}, (h : A ∈ LogicGL) → motive A (provable_of_provable_GL h))
  (TBB : ∀ (n : ℕ), motive (TBB n) (provable_axiomTBB n))
  (mdp : ∀ {A B}, {hAB : (A 🡒 B) ∈ LogicA} → {hA : A ∈ LogicA} →
    motive (A 🡒 B) hAB → motive A hA → motive B (Logic.sumQuasiNormal.mdp hAB hA))
  : ∀ {A}, (h : A ∈ LogicA) → motive A h := by
  intro A h;
  induction LogicA.substlessTBB.ofLogicA h with
  | GL hg => exact GL hg;
  | TBB n => exact TBB n;
  | mdp hAB hA ihAB ihA =>
    exact mdp (hAB := LogicA.substlessTBB.toLogicA hAB) (hA := LogicA.substlessTBB.toLogicA hA)
      (ihAB _) (ihA _);

end


variable [DecidableEq α] {A B : Formula α} {n : ℕ}

lemma provable_neg_boxItr_bot : ∼□^[n]⊥ ∈ @LogicA α := by
  induction n with
  | zero =>
    apply provable_of_provable_GL;
    exact LogicGL.iff_forces.mpr (by grind);
  | succ n ih =>
    have hTBB : TBB n ∈ @LogicA α := provable_axiomTBB n;
    have hK : TBB n 🡒 ∼□^[n]⊥ 🡒 ∼□^[n + 1]⊥  ∈ @LogicGL α := LogicGL.iff_forces.mpr (by grind);
    exact Logic.sumQuasiNormal.mdp (Logic.sumQuasiNormal.mdp (provable_of_provable_GL hK) hTBB) ih;

/-- The easy direction of `LogicA.iff_provable_provable_GL_neg_boxItr_bot_imp`. -/
lemma provable_of_provable_GL_neg_boxItr_bot_imp (h : (∼□^[n]⊥) 🡒 A ∈ LogicGL) : A ∈ LogicA :=
  Logic.sumQuasiNormal.mdp (provable_of_provable_GL h) provable_neg_boxItr_bot


section

/--
  The intrinsic definition of `LogicA` that avoids `subst`, generated by the iterated
  consistency statements `∼□^[n]⊥` in place of the axioms `TBB n` (used for
  `LogicA.substlessInductionGP`).
-/
protected inductive substlessGP : Logic α
  | GL {C : Formula α} : C ∈ LogicGL → LogicA.substlessGP C
  | GP (m : ℕ) : LogicA.substlessGP (∼□^[m]⊥)
  | mdp {C D : Formula α} : LogicA.substlessGP (C 🡒 D) → LogicA.substlessGP C → LogicA.substlessGP D

private lemma substlessGP.eq_LogicA : LogicA.substlessGP (α := α) = LogicA := by
  ext A;
  constructor;
  . intro h;
    induction h with
    | GL h => exact provable_of_provable_GL h;
    | GP n => exact provable_neg_boxItr_bot;
    | mdp _ _ ihAB ihA => exact Logic.sumQuasiNormal.mdp ihAB ihA;
  . intro h;
    induction h using LogicA.substlessInductionTBB with
    | GL h => exact LogicA.substlessGP.GL h;
    | TBB n =>
      have h₁ : LogicA.substlessGP (∼□^[n + 1]⊥ : Formula α) :=
        LogicA.substlessGP.GP (n + 1);
      have h₂ : LogicA.substlessGP ((∼□^[n + 1]⊥) 🡒 TBB n : Formula α) := by
        apply LogicA.substlessGP.GL;
        exact LogicGL.iff_forces.mpr (by grind);
      exact LogicA.substlessGP.mdp h₂ h₁;
    | mdp ihAB ihA => exact LogicA.substlessGP.mdp ihAB ihA;

private lemma substlessGP.toLogicA (h : A ∈ LogicA.substlessGP) : A ∈ LogicA := by
  rwa [←LogicA.substlessGP.eq_LogicA];

private lemma substlessGP.ofLogicA (h : A ∈ LogicA) : A ∈ LogicA.substlessGP := by
  rwa [LogicA.substlessGP.eq_LogicA];

/--
  Induction principle for `LogicA` avoiding `subst`, for the axiomatization by the iterated
  consistency statements: it suffices to handle the `GL` fragment, the axioms `∼□^[n]⊥`,
  and `mdp`.
-/
protected lemma substlessInductionGP
  {motive : (A : Formula α) → A ∈ LogicA → Prop}
  (GL : ∀ {A}, (h : A ∈ LogicGL) → motive A (provable_of_provable_GL h))
  (GP : ∀ (n : ℕ), motive (∼□^[n]⊥) provable_neg_boxItr_bot)
  (mdp : ∀ {A B}, {hAB : (A 🡒 B) ∈ LogicA} → {hA : A ∈ LogicA} →
    motive (A 🡒 B) hAB → motive A hA → motive B (Logic.sumQuasiNormal.mdp hAB hA))
  : ∀ {A}, (h : A ∈ LogicA) → motive A h := by
  intro A h;
  induction LogicA.substlessGP.ofLogicA h with
  | GL hg => exact GL hg;
  | GP n => exact GP n;
  | mdp hAB hA ihAB ihA =>
    exact mdp
      (hAB := LogicA.substlessGP.toLogicA hAB)
      (hA := LogicA.substlessGP.toLogicA hA)
      (ihAB _) (ihA _);

end


open Model Model.World

lemma exists_forces_of_forces_instancesBelow_of_provable (h : A ∈ LogicA) :
  ∃ N : ℕ, ∀ {κ : Type u}, [Nonempty κ] → ∀ (M : Model κ α), [M.IsFiniteGL] → ∀ (x : M.World),
  (∀ n < N, x ⊩[_] TBB n) → x ⊩[_] A := by
  induction h using LogicA.substlessInductionTBB with
  | GL h =>
    use 0;
    intro κ _ M _ x _;
    exact ProvableHilbert.Kripke.soundness h M x;
  | TBB n =>
    use n + 1;
    grind;
  | mdp ihAB ihA =>
    obtain ⟨N₁, ihAB⟩ := ihAB;
    obtain ⟨N₂, ihA⟩ := ihA;
    use max N₁ N₂;
    intro κ _ M _ x hx;
    replace ihAB := ihAB M x (by grind);
    replace ihA := ihA M x (by grind);
    grind;

omit [DecidableEq α] in
lemma root_forces_neg_boxItr_bot_imp
  (h : ∃ N : ℕ, ∀ {κ : Type u}, [Nonempty κ] → ∀ (M : Model κ α), [M.IsFiniteGL] →
    ∀ (x : M.World), (∀ n < N, x ⊩[_] TBB n) → x ⊩[_] A)
  : ∃ N : ℕ, ∀ {κ : Type u}, [Nonempty κ] → ∀ (M : RootedModel κ α), [M.IsFiniteGL] →
  M.root.1 ⊩[_] ((∼□^[N]⊥) 🡒 A) := by
  obtain ⟨N, hN⟩ := h;
  use N;
  intro κ _ M _;
  -- Both `x ⊩[M] ∼□^[N]⊥` and `∀ n < N, x ⊩[M] TBB n` express `N ≤ x.rank`.
  have : Fintype M.World := Fintype.ofFinite _;
  by_contra hC;
  obtain ⟨h₁, h₂⟩ := not_forces_imp.mp hC;
  apply h₂;
  apply hN M.toModel M.root.1;
  intro n hn;
  apply Model.iff_forces_TBB_neq_rank.mpr;
  have hge : ¬ M.root.1.rank < N :=
    fun hc => (forces_neg.mp h₁) (Model.iff_rank_lt_forces_boxItr_bot.mp hc);
  omega;

/-- Deduction-theorem-style `GL`-characterization of `LogicA`. -/
theorem iff_provable_provable_GL_neg_boxItr_bot_imp :
  A ∈ LogicA ↔ ∃ n : ℕ, (∼□^[n]⊥) 🡒 A ∈ LogicGL := by
  constructor;
  . intro h;
    obtain ⟨N, hN⟩ := root_forces_neg_boxItr_bot_imp (exists_forces_of_forces_instancesBelow_of_provable h);
    exact ⟨N, LogicGL.iff_forces_root.mpr hN⟩;
  . rintro ⟨n, h⟩;
    exact provable_of_provable_GL_neg_boxItr_bot_imp h;

/--
  If `A ∉ LogicA`, then `GL ⊬ ◇(⋀A.subfmlsS) 🡒 A`.

  - [AB05, Lemma 51]
-/
lemma not_GL_provable_dia_subfmlsS_imp_of_not_mem_LogicA (h : A ∉ LogicA) :
  ((◇(⋀A.subfmlsS)) 🡒 A) ∉ LogicGL := by
  contrapose! h;
  have h₁ : (∼□^[A.subfmls.prebox.card + 1]⊥ : Formula α) ∈ LogicA := LogicA.provable_neg_boxItr_bot;
  have h₂ : ((◇(⋀A.subfmlsS)) : Formula α) ∈ LogicA :=
    Logic.sumQuasiNormal.mdp
      (Logic.sumQuasiNormal.mem₁ LogicGL.provable_neg_boxItr_bot_imp_dia_subfmlsS) h₁;
  exact Logic.sumQuasiNormal.mdp (Logic.sumQuasiNormal.mem₁ h) h₂;

/--
  A formula outside `LogicA` has a finite rooted `GL` countermodel whose root refutes `A`
  and sees a point at which every instance `□B 🡒 B` of the T axiom for a boxed subformula
  `□B` of `A` holds.

  - [AB05, Lemma 51]
-/
lemma exists_reflexive_countermodel_of_not_mem_LogicA (h : A ∉ LogicA) :
  ∃ (κ : Type u) (_ : Nonempty κ) (M : RootedModel κ α) (_ : M.IsFiniteGL),
  M.root.1 ⊮[_] A ∧ ∃ r : M.World, M.root.1 ≺ r ∧ r ⊩[_] ⋀A.subfmlsS := by
  have := (LogicGL.iff_forces_root (A := (◇(⋀A.subfmlsS)) 🡒 A)).not.mp
    (not_GL_provable_dia_subfmlsS_imp_of_not_mem_LogicA h);
  push Not at this;
  obtain ⟨κ, hne, M, hfgl, hroot⟩ := this;
  obtain ⟨hdia, hnA⟩ := not_forces_imp.mp hroot;
  obtain ⟨r, hr, hrS⟩ := forces_dia.mp hdia;
  exact ⟨κ, hne, M, hfgl, hnA, r, hr, hrS⟩;

/--
  ω-model completeness of `LogicA`: provability, the deduction-theorem form
  `GL ⊢ ∼□^[n]⊥ 🡒 A`, and forcing at the root of every ω-model `M.graftOmega a` (for finite
  rooted `GL` models `M` and points `a` above the root) are equivalent.

  - [Bek90, Lemma 5]
-/
theorem provability_TFAE : [
  A ∈ LogicA,
  ⊢ᵍ[A] (∅ ⟹[1] {A}),
  ⊢ᵍᶜ[A] (∅ ⟹[1] {A}),
  ∀ {κ : Type u}, [Nonempty κ] → ∀ (M : RootedModel κ α), [M.IsFiniteGL] →
    ∀ (a : M.World) (Rra : M.root.1 ≺ a),
    (M.graftOmega ⟨a, fun h => Std.Irrefl.irrefl _ (h ▸ Rra)⟩).root.1 ⊩[_] A,
  ∃ n : ℕ, ((∼□^[n]⊥) 🡒 A) ∈ LogicGL,
].TFAE := by
  tfae_have 1 → 5 := LogicA.iff_provable_provable_GL_neg_boxItr_bot_imp.mp;
  tfae_have 5 → 4 := by
    rintro ⟨n, hGL⟩ κ _ M _ a Rra;
    have := RootedModel.graftOmega.isGL (M := M) (a := ⟨a, fun h => Std.Irrefl.irrefl _ (h ▸ Rra)⟩) Rra;
    exact ProvableHilbert.Kripke.soundness hGL ((M.graftOmega ⟨a, fun h => Std.Irrefl.irrefl _ (h ▸ Rra)⟩).toModel)
      (M.graftOmega ⟨a, fun h => Std.Irrefl.irrefl _ (h ▸ Rra)⟩).root.1
      (forces_neg.mpr RootedModel.graftOmega.root_not_forces_boxItr_bot);
  tfae_have 4 → 1 := by
    intro h;
    by_contra hA;
    obtain ⟨κ, hne, M, hfgl, hroot, r, Rrr, hrS⟩ := exists_reflexive_countermodel_of_not_mem_LogicA hA;
    apply hroot;
    have ha : ∀ B, (□B) ∈ A.subfmls → r ⊩[_] ((□B) 🡒 B) := by
      intro B hB;
      exact forces_fconj.mp hrS _
        (Finset.mem_image_of_mem _ (FormulaFinset.iff_mem_prebox_mem.mpr hB));
    exact RootedModel.graftOmega.mainlemma ⟨r, fun hB => ha _ hB⟩ Rrr Formula.mem_subfmls_self
      |>.2 M.root.1 |>.mp (h M r Rrr);
  tfae_have 1 → 3 := by
    intro h;
    clear tfae_1_to_5 tfae_5_to_4 tfae_4_to_1;
    induction h using LogicA.substlessInductionGP with
    | GL h =>
      apply GentzenWithCutProvable.liftUp;
      apply GentzenWithCutProvable.of_without_cut;
      exact LogicA.iff_provableGentzen_provable_zero.mp (LogicGL.iff_provableGentzen.mp h);
    | GP n => exact GentzenWithCutProvable.neg_boxItr_bot n;
    | mdp ihAB ihA => exact GentzenWithCutProvable.mdp ihAB ihA;
  tfae_have 3 → 4 := by
    intro h κ _ M _ a Rra;
    exact forces_singleton_sequent.mp
      (GentzenWithCutProvable.soundness_graftOmega h M a Rra);
  tfae_have 3 ↔ 2 := LogicA.sequent_TFAE.out 0 1
  tfae_finish;

/--
  A formula is a `LogicA` theorem iff it is forced at the root of every ω-model.

  - [Bek90, Lemma 5]
-/
theorem iff_provable_forces_graftOmega_root :
  A ∈ LogicA ↔
  (∀ {κ : Type u}, [Nonempty κ] → ∀ (M : RootedModel κ α), [M.IsFiniteGL] →
    ∀ (a : M.World) (Rra : M.root.1 ≺ a),
    (M.graftOmega ⟨a, fun h => Std.Irrefl.irrefl _ (h ▸ Rra)⟩).root.1 ⊩[_] A) :=
  LogicA.provability_TFAE.out 0 3

theorem iff_provable_provableGentzenWithCut :
  A ∈ LogicA ↔ ⊢ᵍᶜ[A] (∅ ⟹[1] {A}) :=
  LogicA.provability_TFAE.out 0 2

theorem iff_provable_provableGentzen :
  A ∈ LogicA ↔ ⊢ᵍ[A] (∅ ⟹[1] {A}) :=
  LogicA.provability_TFAE.out 0 1

end LogicA

theorem LogicA_subset_LogicD [DecidableEq α] : @LogicA α ⊆ LogicD := by
  intro A hA;
  obtain ⟨n, h⟩ := LogicA.iff_provable_provable_GL_neg_boxItr_bot_imp.mp hA;
  exact Logic.sumQuasiNormal.mdp (LogicD.provable_of_provable_GL h) LogicD.provable_neg_boxItr_bot;


section axiomD

/-! ### The axiom `D` is not a theorem of `LogicA` -/

open Model Model.World

variable {a : α} {n : ℕ}

abbrev axiomDCountermodel.bad (n : ℕ) : Fin (n + 2) := ⟨1, by omega⟩

/-- The chain `0 ≺ 1 ≺ ⋯ ≺ n + 1` on `Fin (n + 2)`, with `a` false exactly at
`axiomDCountermodel.bad n` and true everywhere else. -/
abbrev axiomDCountermodel (n : ℕ) (_a : α) : RootedModel (Fin (n + 2)) α where
  Rel' := (· < ·)
  Val' x _ := x ≠ axiomDCountermodel.bad n
  root := ⟨0, fun _ hx => Fin.pos_of_ne_zero hx⟩

namespace axiomDCountermodel

instance : (axiomDCountermodel n a).IsFiniteGL where
  finite := inferInstance
instance : (axiomDCountermodel n a).IsGL := Model.instIsGLOfIsFiniteGL

lemma rank_eq (x : (axiomDCountermodel n a).World) : x.rank = (n + 1) - x :=
  finiteLineModel.rank_eq (n := n + 1) (α := α) x

lemma root_rank_eq : (axiomDCountermodel n a).root.1.rank = n + 1 := by
  simpa using rank_eq (a := a) (axiomDCountermodel n a).root.1;

lemma forces_box_atom_of_ne_root {x : (axiomDCountermodel n a).World} (hx : 0 < x) :
  x ⊩[_] (□(#a) : Formula α) := by grind

lemma root_not_forces_box_atom : ¬(axiomDCountermodel n a).root.1 ⊩[_] (□(#a) : Formula α) :=
  not_forces_box.mpr ⟨bad n, by grind, by grind⟩

lemma root_not_forces_axiomD_consequent :
  ¬(axiomDCountermodel n a).root.1 ⊩[_] ((□(#a) : Formula α) ⋎ □(#a)) :=
  not_forces_or.mpr ⟨root_not_forces_box_atom, root_not_forces_box_atom⟩

lemma root_forces_axiomD_antecedent :
  (axiomDCountermodel n a).root.1 ⊩[_] (□((□(#a) : Formula α) ⋎ □(#a))) :=
  forces_box.mpr fun _ hy =>
    forces_or.mpr <| Or.inl <| forces_box_atom_of_ne_root hy

lemma root_forces_neg_boxItr_bot :
  (axiomDCountermodel n a).root.1 ⊩[_] (∼(□^[n]⊥) : Formula α) := by
  apply forces_neg.mpr;
  intro hc;
  have h := Model.iff_rank_lt_forces_boxItr_bot.mpr hc;
  rw [root_rank_eq] at h;
  omega;

end axiomDCountermodel

/-- Axiom `D` (`□(□A ⋎ □B) 🡒 (□A ⋎ □B)`), specialized to `A = B = #a`, is not a theorem of
`LogicA`. -/
theorem LogicA.not_provable_axiomD [DecidableEq α] {a : α} :
  ((□((□#a) ⋎ □#a)) 🡒 ((□#a) ⋎ □#a)) ∉ @LogicA α := by
  rw [LogicA.iff_provable_provable_GL_neg_boxItr_bot_imp];
  rintro ⟨n, hGL⟩;
  have h := LogicGL.concrete_root_forces_of_mem (axiomDCountermodel n a) hGL
    axiomDCountermodel.root_forces_neg_boxItr_bot;
  rcases forces_imp.mp h with h | h;
  · exact h axiomDCountermodel.root_forces_axiomD_antecedent;
  · exact axiomDCountermodel.root_not_forces_axiomD_consequent h;

theorem not_LogicD_subset_LogicA [DecidableEq α] {a : α} : ¬(@LogicD α ⊆ LogicA) := by
  intro h;
  exact LogicA.not_provable_axiomD (a := a) (h (LogicD.provable_axiomD (A := #a) (B := #a)));

/-- `LogicA` is a proper sublogic of `LogicD`; folklore, with no source cited. -/
theorem LogicA_ssubset_LogicD [DecidableEq α] [Inhabited α] : @LogicA α ⊂ LogicD :=
  ⟨LogicA_subset_LogicD, not_LogicD_subset_LogicA (a := default)⟩

end axiomD

end
